name: HOTFIX AND RELEASE VERSION BUMP
  
on:
  pull_request:
    branches:
      - 'production_release_**'
    types: [ closed ]
  create:
  
jobs:
  calculate-version:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'create' &&  ${{ contains(github.ref, 'refs/heads/production_release') }})

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          chmod +x ./.github/intall-py-dependecies.sh
          ./.github/intall-py-dependecies.sh
          
      - name: Run Computer Version Script
        id: semver
        run:  echo "::set-output name=matrix::$(python ./.github/hotfix_release.py $GITHUB_REF)"
          
  update-yaml:
    needs: calculate-version
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.calculate-version.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Version on Yaml File
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{ matrix.file }}
          propertyPath: info.version
          value: ${{ matrix.version }}
          commitChange: true
          updateFile: true
          targetBranch: ${{ needs.version.outputs.branch_name }}
          masterBranchName: master
          createPR: false
          branch:  ${{ needs.version.outputs.branch_name }}
          message: Bump version to ${{ matrix.version }} in ${{ matrix.file }}
